version: '3'
services:
  server:
    container_name: store_server
    build:
      context: .
      dockerfile: ./docker/${ENVIRONMENT}/Dockerfile
      args:
        - NODE_ENV=${ENVIRONMENT}
    restart: unless-stopped
    networks:
      - internal
      - proxy-net
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${ENVIRONMENT}

networks:
  internal:
    name: store_internal
    driver: bridge
  proxy-net:
    name: store_external
    external: true